---
- name: "apt-get update"
  apt:
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest    

- name: "Install common packages"
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - htop
    - tree
    - git
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - httpie
