#!/usr/bin/env ansible-playbook
---
- hosts: robcloud
  become: true
  become_method: sudo

  tasks:
    - name: Update all deb packages to their latest version
      apt:
        name: "*"
        state: latest    
        update_cache: yes
          
    - name: Update all snap packages to their latest version
      command: "snap refresh"
